### ISSUE TITLE
C1 capacitor

### ISSUE THREAD

**Issue by gdeda** [makerhqsac/piprog#2]
Is that 100 nF capacitor put properly?
In schematics, it lies between GND and VCC of the ICSP socket (is that in parallel between them going to  GND and 3,3V of the RPi?)
In the BRD file and according to photos, it lies somewhere between the ZIF socket pin 40 and the I2C socket; the ICSP socket looks like uninvolved. Moreover, I can't see the GND of the capacitor wired somewhere...
Am I missing something?

**Comment by masha256** [comment]
The labeling of the ICSP pin is not great - I should have labeled it 3.3V instead of VCC. Also, I should have put it somewhere better on the schematic. Its simply a decoupling cap. It lies between the RPi 3.3V and GND - and is there to just provide a little more decoupling. Probably not needed but just wanted to be safe. You can see it a little more clear here: https://github.com/makerhqsac/piprog/blob/master/images/assembly2a.png

Its placement near the ZIF is purely coincidence - its not related to the ZIF usage. It was a convident place to intersect the 3.3V line. On the GND side, its connected to the GND ground plane via thermal reliefs.
